clc; clear all; close all;
L=input("Enter the UpSampling Factor");
N=input("Enter the Length of the input signal");
f1=input("Enter the frequency of first sinusoidal signal");
f2=input("Enter the frequency of second sinusoidal signal");
n=0:N-1;
x=sin(2*pi*f1*n)+sin(2*pi*f2*n);
y=interp(x,L);
subplot(2,1,1);
stem(n,x(1:N));
title('Input Sequence');
xlabel('Time (n)');
ylabel('Amplitude');
subplot(2,1,2);
m=0:N*L-1;
stem(m,y(1:N*L));
title('Interpolated Sequence');
xlabel('Time (n)');
ylabel('Amplitude');